name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Extract short SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Pull, tag, and push Docker image
        run: |
          docker pull ghcr.io/${GITHUB_REPOSITORY}:${COMMIT_SHORT_SHA}-test
          docker tag ghcr.io/${GITHUB_REPOSITORY}:${COMMIT_SHORT_SHA}-test ghcr.io/${GITHUB_REPOSITORY}:${{ steps.tag_version.outputs.new_tag }}
          docker tag ghcr.io/${GITHUB_REPOSITORY}:${COMMIT_SHORT_SHA}-test ghcr.io/${GITHUB_REPOSITORY}:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}:${{ steps.tag_version.outputs.new_tag }}
          docker push ghcr.io/${GITHUB_REPOSITORY}:latest
